name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set variables
      id: vars
      run: |
        echo ::set-output name=docker_image::monder/haproxy-ingress:$(git rev-parse --short=7 ${{ github.sha }})
    - name: Build docker image
      run: |
        docker build . --file build/Dockerfile --tag ${{ steps.vars.outputs.docker_image }}
    - name: Login to registry
      run: |
        echo ${{ secrets.DockerHub }} | docker login --username monder --password-stdin
    - name: Push docker image
      run: |
        docker push ${{ steps.vars.outputs.docker_image }}
